### PR TITLE
Added countryId to companies endpoint

### PR DESCRIPTION
**Pull request by agnessa**

### CODE REVIEW

**Comment by tiagojsag** [comment]
feels like a test's missing here

**Comment by agnessa** [comment]
> feels like a test's missing here

Tiago is chasing me about tests - my job is done here, my life is complete! 💃 🎉 ❤️

**Comment by agnessa** [comment]
The endpoint is already covered by a schema spec, so I just updated the schema with the new property.

**Comment by tiagojsag** [comment]
ok, so there's probably an issue in those tests, as they were not failing before you updated them.

**Comment by agnessa** [comment]
Added countryId to companies search endpoint (also sources and destinations as all 3 use shared functionality and it was easier to do that than differentiate)

**Comment by sorodrigo** [comment]
Ready to go!

**Pull request merged**
