### PR TITLE
Feature/expand map buckets

### PR DESCRIPTION
**Pull request by agnessa**
- renamed `bucket_3` -> `dual_layer_buckets`, `bucket_5` -> `single_layer_buckets`
- `dual_layer_buckets` needs to be 3 elements (values rescaled by adding an element in between)
- `single_layer_buckets` can be variable length; because of that there is now an sql function which calculates the bucket for a given value in the `node_attributes` endpoint (we used to have a `CASE` statement there, but that wouldn't work for variable length arrays)
- while making the changes to the `map_layers` controller I noticed it still uses v2 serializers, so I added v3 versions so that it's easier to get rid of v2 in the future
- did not add the capability to populate buckets automatically

`bundle exec rake db:migrate`

### CODE REVIEW

**Comment by agnessa** [comment]
https://github.com/Vizzuality/trase/issues/179

Did not add the capability to populate buckets automatically, as I'm not sure at which point this is supposed to happen (import script? admin tool?) and also I think there are more properties that could benefit from default values, and not sure if providing those is in scope.

I believe all of these properties could be prepopulated from data in `flows`, and to me it would make sense to either do it for all of them or none:
    - `map_attributes#years`
    - `map_attributes#single_layer_buckets`
    - `map_attributes#double_layer_buckets`
    - `download_attributes#years`
    - `ind/qual/quant properties#is_temporal`
    - `recolor_by_attributes#years`
    - `recolor_by_attributes#min/max_value`
    - `resize_by_attributes#years`

**Comment by agnessa** [comment]
@sorodrigo I believe this is ready for you to look at. The first thing to look into is handling the 4x4 grid for dual layers. Not sure what needs doing with single layers at this point (eventually they need to support variable length buckets.)

**Comment by tiagojsag** [comment]
Backend changes look good, but can't be merged until we do the FE changes, due to the increase in number of buckets

**Comment by tiagojsag** [comment]
This will need another iteration once https://github.com/Vizzuality/trase/issues/323 is done, but for now we should merge, to avoid rebase nightmare (and to avoid me having to rollback my database, im lazy).

**Pull request merged**
