### PR TITLE
Feature/node attributes v3

### PR DESCRIPTION
**Pull request by agnessa**
/contexts/:context_id/nodes/attributes

### CODE REVIEW

**Comment by tiagojsag** [comment]
could you update the frontend config too, please?

**Comment by agnessa** [comment]
I think the frontend was already updated, as in the url to use - or you mean sth different? I just rebased.

**Comment by tiagojsag** [comment]
oh, no, must have missed that, sorry

**Comment by tiagojsag** [comment]
should we add response structure tests as part of this PR?

**Comment by agnessa** [comment]
would be good, but I won't have time to do it before Christmas; there are more endpoints that are missing these tests, so an alternative would be to add all the missing ones in a separate PR.

**Pull request merged**
