### PR TITLE
fix: restores scroll on page change

### PR DESCRIPTION
**Pull request by sorodrigo**
Restores page's scroll to top on navigation.

Addresses #382

### CODE REVIEW

**Comment by tiagojsag** [comment]
Seems to only work on the first try, after that it fails.

**Comment by sorodrigo** [comment]
@tiagojsag I fixed all our issues regarding the scroll restoration.
@tsubik I think I solved the safari issue #333 

Please review :)

**Comment by tsubik** [comment]
Hmm, I still have this language selector issue :/ @sorodrigo 
About the scroll restoration, surely we should restore to the top when navigating to a new page. Although, as a user, when clicking back button (especially on mobile), I would expect to see the exact same spot where I was, not the top of the page.

**Comment by sorodrigo** [comment]
> I would expect to see the exact same spot where I was, not the top of the page.

That's easy to achieve, thoughts about this @tiagojsag ?

**Comment by tiagojsag** [comment]
not super concerned about restoring scroll when pressing back, to be honest. If it's easy to do (a couple of hours) sure, let's go for it, but otherwise I'm happy scrolling to the top

**Comment by tiagojsag** [comment]
when I use back, I am not taken to the top of the page, but rather stay in the same scroll position as i was when I hit the back button. This feels weird, I think perhaps a better solution would be to scroll to the top too?

**Comment by tsubik** [comment]
Right, it feels weird, but using that restore-scroll I was able to make `about` page works just fine, going back and forward to left scroll positions, but when opening the new page going to the top. Unfortunately, not profile pages :/. What I also noticed there is always the second redirect caused by locale selector when changing page, probably unnecessarily.

**Pull request merged**
