### PR TITLE
Feature/logistic map indonesia

### PR DESCRIPTION
**Pull request by Bluesmile82**
This PR adds the new Indonesia - Palm oil context to the logistics map:

- Add a layer for Palm Oil and texts
- Add parent companies of the mills to the map
- Add some attributes to the tooltip
- Fix download modal

image

### CODE REVIEW

**Comment by sorodrigo** [comment]
Well done! Three things to change maybe:

- In the next screenshot you can see a blank when no data is available, maybe we should show `N/A`?
Screen Shot 2019-06-12 at 17 02 41

- In the selector because only Indonesia is showing when clicking we don't see any changes, this should be disabled so that the item is read only, see the Recolor By selector on any non subnational context.

- Finally, we're reusing the crushing facilities icon for the mills, speak with Fanny to get a different icon and perhaps a different color? 🌬

**Comment by Bluesmile82** [comment]
Updated the Carto layer. Still some questions to be answered. The crushing facilities icon for the mills was suggested by Pablo. Maybe @fannycc (@Fanny) has a different option

**Comment by fannycc** [comment]
@Bluesmile82 I'd need more context about that icon. Which one is it and for what we are using it?

**Comment by fannycc** [comment]
@Bluesmile82 @sorodrigo let's ask them about the mills layer in Indonesia to know what type of data gives. None seems to know it, not even Pablo. Can you guys ask?

**Comment by sorodrigo** [comment]
well done!! 💯

**Pull request merged**
