### PR TITLE
Feature/quick facts

### PR DESCRIPTION
**Pull request by agnessa**
https://www.pivotaltracker.com/story/show/167778490

```
{
   "data":[
      {
         "countryId":12,
         "facts":[
            {
               "year":2017,
               "attributeId":29,
               "total":38181449.8828643
            }
         ]
      },
      {
         "countryId":23,
         "facts":[
            {
               "year":2017,
               "attributeId":29,
               "total":1603570.977733
            }
         ]
      },
      {
         "countryId":27,
         "facts":[
            {
               "year":2017,
               "attributeId":29,
               "total":114599167.987056
            }
         ]
      },
      {
         "countryId":176,
         "facts":[
            {
               "year":2017,
               "attributeId":29,
               "total":10477999.9998733
            }
         ]
      }
   ],
   "meta":{
      "attributes":[
         {
            "id":29,
            "displayName":"Trade volume",
            "unit":"t",
            "tooltipText":"Amount of the traded commodity (tons). The total value is a composite of traded sub-products, which are converted to their original raw equivalents and then aggregated. For example exports of soy cake and soy oil are converted to soybean equivalents in the areas of production, where farmers are just producing beans."
         }
      ]
   }
}
```

### CODE REVIEW

**Comment by Bluesmile82** [comment]
Isn't this the same endpoint as the node_stats? Why do we need an additional endpoint?

**Comment by agnessa** [comment]
I don't think node stats can give us stats per country - it returns data for top 10 nodes (destinations), whereas this gives a total per each country in a commodity. @jesusgonzalezrivera ?

**Comment by Bluesmile82** [comment]
Ok, I think I was confused about the source-destination. Then we won't need extra indicators in the top 10, Just volume. @jesusgonzalezrivera  

But maybe we will need some other indicators in the future in this endpoint. They can come as some other objects in the data.

**Comment by jesusgonzalezrivera** [comment]
Exactly, it is like Agnieska says, `node_stats` for destination countries and `countries_facts` for source country

**Comment by agnessa** [comment]
For now this returns just one fact per country (Volume); will be up to 2 facts going forward

**Pull request merged**
