### PR TITLE
Update rails to 5.2.1

### PR DESCRIPTION
**Pull request by tiagojsag**
Because the best way to fix https://github.com/Vizzuality/trase/network/alert/Gemfile.lock/loofah/open is by updating the whole stack

### CODE REVIEW

**Comment by tiagojsag** [comment]
rebased

**Comment by agnessa** [comment]
These deprecations remain:

```
DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "ts_rank(name_tsvector, to_tsquery('simple', ''' ' || 'so' || ' ''' || ':*'), 0) DESC". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from call_with_query_term at /Users/agnessa/workspace/trase-api/app/services/concerns/api/v3/dashboards/call_with_query_term.rb:13)
..DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "ts_rank(name_tsvector, to_tsquery('simple', ''' ' || 'afg' || ' ''' || ':*'), 0) DESC". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from call_with_query_term at /Users/agnessa/workspace/trase-api/app/services/concerns/api/v3/dashboards/call_with_query_term.rb:13)
..DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "ts_rank(name_tsvector, to_tsquery('simple', ''' ' || 'bra' || ' ''' || ':*'), 0) DESC". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from call_with_query_term at /Users/agnessa/workspace/trase-api/app/services/concerns/api/v3/dashboards/call_with_query_term.rb:13)
..DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "ts_rank(name_tsvector, to_tsquery('simple', ''' ' || 'rus' || ' ''' || ':*'), 0) DESC". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from call_with_query_term at /Users/agnessa/workspace/trase-api/app/services/concerns/api/v3/dashboards/call_with_query_term.rb:13)
..DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "ts_rank(name_tsvector, to_tsquery('simple', ''' ' || 'ubi' || ' ''' || ':*'), 0) DESC". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from call_with_query_term at /Users/agnessa/workspace/trase-api/app/services/concerns/api/v3/dashboards/call_with_query_term.rb:13)
......DEPRECATION WARNING: The success? predicate is deprecated and will be removed in Rails 6.0. Please use successful? as provided by Rack::Response::Helpers. (called from block (3 levels) in <top (required)> at /Users/agnessa/workspace/trase-api/spec/controllers/api/v3/newsletter_subscriptions_controller_spec.rb:8)
```

I think Marta fixed similar ones in CW: https://github.com/Vizzuality/climate-watch/pull/697

**Comment by tiagojsag** [comment]
here you go

**Comment by agnessa** [comment]
👍

**Pull request merged**
