### PR TITLE
Feat: team page

### PR DESCRIPTION
**Pull request by sorodrigo**
This PR includes:
- New Team page at `/about/team`.
- New Team Member page at `/about/team/:member`.
- Renames sidebar to adhere to current naming convention.
- Refactors static pages component and neighbours.
team-page

- [x] Add team groups
- [x] Connect to real API

### CODE REVIEW

**Comment by sorodrigo** [comment]
Ready!

**Comment by tiagojsag** [comment]
@sorodrigo made some changes, let me know what you think

**Comment by sorodrigo** [comment]
I would namespace the Team actions, and use `PureComponent` in the Team component but apart from that looks good.

**Comment by tiagojsag** [comment]
thanks for the tips

**Pull request merged**
