### PR TITLE
Feat/country profile links

### PR DESCRIPTION
**Pull request by tomasmoose**
## Pivotal Tracker

https://www.pivotaltracker.com/story/show/171568692

## Description

Profile links for country profiles, reusing the ones we had previously only parsing is a bit different for the links. Also fixed a small issue where we try to update state on a unmounted component. `banner.component` 

## Testing instructions

Test both export/import countries, make sure links correspond to the correct page.

### CODE REVIEW

**Comment by tomasmoose** [comment]
Will block this until we have a solution for country (importers) as we dont have context.

**Comment by tomasmoose** [comment]
We will only show the links if we have a context @Bluesmile82

**Comment by Bluesmile82** [comment]
Please, solve the conflict so we can merge

**Comment by Bluesmile82** [comment]
Should we merge this? Just solving the conflict before

**Comment by tomasmoose** [comment]
> Should we merge this? Just solving the conflict before

hi will solve this today @Bluesmile82

**Pull request merged**
