### PR TITLE
Feature/responsive explore page

### PR DESCRIPTION
**Pull request by tsubik**
- Making the explore page more responsive, adding the mobile menu for small resolutions
- Showing the world map with the link to the explore page on the home page for all resolutions
- Fixing a year selector so changing the year updates flows on the world map
- Fixing proper context load for the world map
- Adding support for touch events for a year selector

explore-page-responsive

Home page

responsive-homepage-worldmap

### CODE REVIEW

**Comment by tsubik** [comment]
I'm going to replace the current year selector with a normal dropdown.

**Comment by sorodrigo** [comment]
@tsubik we can't do that, because in the near future we will re-enable multiple year selection.

**Comment by tiagojsag** [comment]
- [ ] "SELECT BOTH A COUNTRY AND A COMMODITY" font is incorrect
- [ ] Popups show up offcanvas (test with china for indonesian palm oil)
- [ ] I'm wondering if we should put a message like "if you want to explore the full supply chain, visit trase.earth on a computer" or sorts. My concern is that first time users may think this is it.

**Comment by tiagojsag** [comment]
Almost there, just a couple of thing missing to be perfect:
- on an actual phone, there's a weird effect if you click on any country on the map.
- seems like the tooltip only shows up if you click on the flow itself, which is really hard to do on a phone.

**Comment by tsubik** [comment]
Both should be fixed now @tiagojsag

**Pull request merged**
