### PR TITLE
Return summary of selected filters as y value label

### PR DESCRIPTION
**Pull request by agnessa**
e.g. 'BR / SOY / BUNGE'

### CODE REVIEW

**Comment by tiagojsag** [comment]
no tests? :(

**Comment by agnessa** [comment]
I already forgot what this was for, would it still be useful @sorodrigo or will it break things if we add tests and merge?

**Comment by sorodrigo** [comment]
It won't break stuff but designs changed so it won't be used :/

**Comment by agnessa** [comment]
Out with it then!

**Pull request closed without merging**
