### PR TITLE
Fix/click through arrows

### PR DESCRIPTION
**Pull request by agnessa**
Adds a `profile` flag to inform if profiles exist for given node type. Also fixes funny capitalisation.

https://www.pivotaltracker.com/story/show/163590977
https://www.pivotaltracker.com/story/show/163591074

screenshot 2019-01-31 at 13 00 43

### CODE REVIEW

**Comment by sorodrigo** [comment]
@agnessa 
Ok I fixed the profile-actor table links to the profile-place page. I found a similar case in the `profile-place` page. We have links in the mini-sankey that go to companies, but in the countries we don't. Currently we achieve this by either passing a page to the mini-sankey or not passing it. Do you think we should also handle this on the backend given that country profiles are coming? Or should we address that when we start the country profiles?

**Comment by agnessa** [comment]
I wouldn't fix it now.

**Comment by sorodrigo** [comment]
Ready for reviewing!

**Comment by sorodrigo** [comment]
I added a regression test, will merge!

**Pull request merged**
